config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users #順番を上にした
  
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get 'search' => 'search#search', as: 'search'
  
  resources :users, only: [:show,:index,:edit,:update] do
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
    
  resources :books do
    resources :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image, destroy: false

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。親はfollowed_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  
  
  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  # 中間テーブルを介して「followed」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :followed
  
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50 }
  
  def followed_by?(user)
    passive_relationships.find_by(followed_id: user.id).present?
  end
  
  def User.search(search, user_or_book, how_search)
    if user_or_book == "user"
      if how_search == "match"
        User.where(['name LIKE ?', "#{search}"])
      elsif how_search == "forward"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "backward"
        User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "partical"
        User.where(['name LIKE ?', "%#{search}%"])
      else
        User.none
      end
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! ,only: [:index, :show, :edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>followes</th>
		<th><%= link_to user.followings.count, follows_user_path(user.id) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
	</tr>
</table>

<% if current_user == user %>
	<div class="row">
		<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% end %>

<% if current_user != user %>
	<% if user.followed_by?(current_user) %>
		<p><%= link_to "フォローを外す", user_relationship_path(user.id, current_user.id), method: :delete %></p>
	<% else %>
		<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followers.html.erb
<div class="container">
	<div class="row">
		<h2>Follower Users</h2>
		<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td><span>フォロー数：</span><%= user.followings.count %></td>
						<td><span>フォロワー数：</span><%= user.followers.count %></td>
						<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	</div>
</div>

app/views/users/follows.html.erb
<div class="container">
	<div class="row">
		<h2>Follow Users</h2>
		<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td><span>フォロー数：</span><%= user.followings.count %></td>
						<td><span>フォロワー数：</span><%= user.followers.count %></td>
						<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			
			<h2>New book</h2>
			<%= render 'books/form', book: @book %>
		</div>
		
		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>
			
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name %></td>
						<td><p>フォロー数:<%= user.followings.count %></p></td>
						<td><p>フォロワー数:<%= user.followers.count %></p></td>
						<td>
							<% if current_user != user %>
								<% if user.followed_by?(current_user) %>
									<p><%= link_to "フォローを外す", user_relationship_path(user.id,current_user.id), method: :delete %></p>
								<% else %>
									<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
								<% end %>
							<% end %>
						</td>
						<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
	
			<h2>New book</h2>
			<%= render 'books/form', book: @book %>
		</div>
	
		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<%= render 'books/index', books: @books %>
			<!--books一覧 -->
		</div>
	</div>
</div>